export const ERROR_CODES = {
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",

  FILE_REQUIRED: "FILE_REQUIRED",
  CONTENT_REQUIRED: "CONTENT_REQUIRED",

  YOUTUBE_INVALID_URL: "YOUTUBE_INVALID_URL",
  YOUTUBE_TRANSCRIPT_FAILED: "YOUTUBE_TRANSCRIPT_FAILED",
  YOUTUBE_TRANSCRIPT_BLOCKED: "YOUTUBE_TRANSCRIPT_BLOCKED",
  YOUTUBE_TRANSCRIPT_UNAVAILABLE: "YOUTUBE_TRANSCRIPT_UNAVAILABLE",
  YOUTUBE_AUDIO_DOWNLOAD_FAILED: "YOUTUBE_AUDIO_DOWNLOAD_FAILED",
};
